/*
 * todo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiError {
    /// HTTP Status Code
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "title")]
    pub title: String,
}

impl ApiError {
    pub fn new(status: i32, title: String) -> ApiError {
        ApiError { status, title }
    }
}
