/*
 * todo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostTodoRequest {
    #[serde(rename = "todo")]
    pub todo: String,
}

impl PostTodoRequest {
    pub fn new(todo: String) -> PostTodoRequest {
        PostTodoRequest { todo }
    }
}
