/*
 * todo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostTodoResponse {
    #[serde(rename = "lastInsertId")]
    pub last_insert_id: i32,
}

impl PostTodoResponse {
    pub fn new(last_insert_id: i32) -> PostTodoResponse {
        PostTodoResponse { last_insert_id }
    }
}
