/*
 * todo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Todo {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "todo")]
    pub todo: String,
}

impl Todo {
    pub fn new(id: i32, todo: String) -> Todo {
        Todo { id, todo }
    }
}
