/*
 * todo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TodoResponse {
    #[serde(rename = "todoList")]
    pub todo_list: Vec<crate::models::Todo>,
}

impl TodoResponse {
    pub fn new(todo_list: Vec<crate::models::Todo>) -> TodoResponse {
        TodoResponse { todo_list }
    }
}
